import Link from "next/link";
import { Code, DocHeader, DocSection, DocsShell, Note } from "@/components/docs/DocsShell";

export default function SdkPage() {
  return <DocsShell current="/docs/sdk"><DocHeader eyebrow="RUNTIME / SDK QUICKSTART" title="Compose your own agent runner." description="The core package exports the loop, prompt builder, built-in tools, session store, and event types. You provide an AI SDK v5 LanguageModel and decide how to approve changes and present the run." />
    <DocSection id="install" title="Install the packages"><p>Add the runtime and a provider package to your Node.js application. The Node environment adapter is a separate package subpath.</p><Code>{"npm install @astracollab/not-another-harness ai @ai-sdk/anthropic zod"}</Code><p>The runtime declares AI SDK and Zod as peer dependencies. Use versions compatible with the installed runtime.</p></DocSection>
    <DocSection id="run" title="Create a run"><p>Build a model with your chosen AI SDK provider, create tools rooted at your workspace, then call <code className="font-mono text-[11px] text-zinc-300">runAgent</code>. The core loop accepts a complete system prompt and a tool map.</p><Code language="ts">{"import {\n  buildSystemPrompt,\n  createCodingTools,\n  runAgent,\n} from \"@astracollab/not-another-harness\";\nimport { createNodeEnvironment } from\n  \"@astracollab/not-another-harness/node\";\nimport type { LanguageModel } from \"ai\";\n\ndeclare const model: LanguageModel; // create with an AI SDK v5 provider\n\nconst cwd = process.cwd();\nconst tools = createCodingTools(createNodeEnvironment(cwd), {\n  withBash: false,\n  approveToolCall: async (toolName, input) =>\n    requestApproval(toolName, input),\n});\n\nconst run = runAgent({\n  model,\n  prompt: \"explain the session refresh path\",\n  system: buildSystemPrompt({ cwdLabel: cwd }),\n  tools,\n  maxSteps: 20,\n});"}</Code><Note title="Approval callback">The SDK allows mutating tool calls when <code>approveToolCall</code> is omitted. Connect this callback to your host application&apos;s approval policy; do not use an unconditional allow callback unless that is the intended trust model.</Note></DocSection>
    <DocSection id="consume" title="Consume events and result"><p>Listen to the async stream for live progress. Then await the result for the final text, stop reason, usage totals, transcript, and number of compactions.</p><Code language="ts">{"for await (const event of run.events) {\n  if (event.type === \"text-delta\") {\n    renderText(event.text);\n  } else if (event.type === \"tool-call\") {\n    showToolCall(event.toolName, event.input);\n  } else if (event.type === \"tool-result\") {\n    showToolResult(event.output, event.isError);\n  }\n}\n\nconst result = await run.result;\nshowCompletion(result.reason, result.usage);"}</Code><p>For all event variants and cancellation behavior, see <Link href="/docs/events" className="text-violet-200 hover:text-white">streaming events</Link>. For the defaults behind <code className="font-mono text-[11px] text-zinc-300">maxSteps</code> and compaction, see <Link href="/docs/agent-loop" className="text-violet-200 hover:text-white">the agent loop</Link>.</p></DocSection>
    <DocSection id="persistence" title="Persist sessions"><p>The core runtime returns the full transcript in the result and accepts prior AI SDK messages through the <code className="font-mono text-[11px] text-zinc-300">messages</code> option. For JSONL persistence, the package exports <code className="font-mono text-[11px] text-zinc-300">createJsonlSessionStore</code>, with append and load methods. The CLI uses that store for its session behavior.</p><Code language="ts">{"import { createJsonlSessionStore } from\n  \"@astracollab/not-another-harness\";\n\nconst session = createJsonlSessionStore(\".nah/session.jsonl\");\nconst previousMessages = await session.load();\n\nconst run = runAgent({ ...options, messages: previousMessages });\nconst result = await run.result;\nawait session.append(result.messages);"}</Code></DocSection>
  </DocsShell>;
}
