import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { Code, DocHeader, DocSection, DocsShell, Note } from "@/components/docs/DocsShell";

export default function InstallationPage() {
  return <DocsShell current="/docs/installation"><DocHeader eyebrow="GET STARTED / INSTALLATION" title="Run your first session." description="The NAH CLI runs locally in the current project directory. It needs Node.js 20.6 or newer and credentials for the model provider you choose." />
    <DocSection id="install" title="Install the CLI"><p>Install the published CLI globally with npm:</p><Code>{"npm install -g @astracollab/nah\nnah --help"}</Code><p>Run <code className="rounded bg-white/[0.06] px-1.5 py-0.5 font-mono text-[11px] text-zinc-300">nah</code> from a project directory to start an interactive session. Give it a task directly to start with a prompt.</p><Code>{"cd your-project\nnah \"trace the login flow and summarize it\""}</Code></DocSection>
    <DocSection id="provider" title="Choose a model provider"><p>The default model is <code className="rounded bg-white/[0.06] px-1.5 py-0.5 font-mono text-[11px] text-zinc-300">anthropic:claude-sonnet-4-5</code>. Set the matching API key, or pass a provider and model ID with <code className="rounded bg-white/[0.06] px-1.5 py-0.5 font-mono text-[11px] text-zinc-300">--model</code>.</p><Code>{"export ANTHROPIC_API_KEY=your-key\n# Or use OpenAI:\nexport OPENAI_API_KEY=your-key\nnah --model openai:gpt-4.1 \"review the error handling\""}</Code><p>Provider choices supported by the CLI are Anthropic, OpenAI, OpenRouter, and OpenAI-compatible endpoints. OpenRouter accepts <code className="rounded bg-white/[0.06] px-1.5 py-0.5 font-mono text-[11px] text-zinc-300">OPENROUTER_API_KEY</code> (or <code className="rounded bg-white/[0.06] px-1.5 py-0.5 font-mono text-[11px] text-zinc-300">OPENAI_API_KEY</code>) and an optional <code className="rounded bg-white/[0.06] px-1.5 py-0.5 font-mono text-[11px] text-zinc-300">OPENROUTER_BASE_URL</code>. OpenAI-compatible endpoints use <code className="rounded bg-white/[0.06] px-1.5 py-0.5 font-mono text-[11px] text-zinc-300">NAH_API_KEY</code> and <code className="rounded bg-white/[0.06] px-1.5 py-0.5 font-mono text-[11px] text-zinc-300">NAH_BASE_URL</code> (or the corresponding <code className="rounded bg-white/[0.06] px-1.5 py-0.5 font-mono text-[11px] text-zinc-300">OPENAI_COMPATIBLE_*</code> variables).</p></DocSection>
    <DocSection id="permissions" title="Understand permissions"><p>Interactive mode defaults to <code className="rounded bg-white/[0.06] px-1.5 py-0.5 font-mono text-[11px] text-zinc-300">ask</code>: read-only tools run without prompting, while edit, write, and bash calls require approval. Choose <code className="rounded bg-white/[0.06] px-1.5 py-0.5 font-mono text-[11px] text-zinc-300">readonly</code> to deny mutations or <code className="rounded bg-white/[0.06] px-1.5 py-0.5 font-mono text-[11px] text-zinc-300">yolo</code> to allow them.</p><Code>{"nah --permissions readonly \"inspect the auth module\"\nnah --permissions ask \"fix the typo in README.md\""}</Code><Note title="Non-interactive behavior">Print and JSON modes default to <code>yolo</code> because they cannot ask for approval in the terminal. Use <code>--permissions readonly</code> or <code>--permissions ask</code> to override that default.</Note></DocSection>
    <DocSection id="next" title="Next steps"><p>Learn how budgets and stopping conditions work in the <Link href="/docs/agent-loop" className="text-violet-200 hover:text-white">agent loop guide</Link>, or browse the <Link href="/docs/cli" className="text-violet-200 hover:text-white">CLI reference</Link>.</p></DocSection>
  </DocsShell>;
}
