import Link from "next/link";
import { Code, DocHeader, DocSection, DocsShell, Note } from "@/components/docs/DocsShell";

export default function AgentLoopPage() {
  return <DocsShell current="/docs/agent-loop"><DocHeader eyebrow="RUNTIME / AGENT LOOP" title="A turn, from prompt to finish." description="NAH keeps the coding-agent cycle in ordinary code you can inspect: prepare context, stream one model response, execute its tool calls, record the result, then decide whether to continue." />
    <DocSection id="layers" title="Two layers work together"><p>The core package supplies <code className="font-mono text-[11px] text-zinc-300">runAgent</code>, the prompt builder, coding tools, and session primitives. It accepts an AI SDK v5 language model and does not pick a provider or own a terminal UI.</p><p>The CLI assembles the application around that core: it resolves credentials and a model, discovers project instruction files, adds task tracking, memory and optional delegation, selects local or sandboxed tools, applies a permission policy, and persists the conversation.</p><Link href="/docs/sdk" className="text-violet-200 hover:text-white">Build on the core SDK →</Link></DocSection>
    <DocSection id="sequence" title="What happens during a turn"><ol className="ml-5 list-decimal space-y-2"><li><strong className="text-zinc-200">Prepare the request.</strong> The prompt, prior session messages, the system prompt, discovered <code>AGENTS.md</code>/<code>CLAUDE.md</code> context, and — when memory is enabled — the memory index for this turn.</li><li><strong className="text-zinc-200">Start a step.</strong> One AI SDK streaming call with the current transcript and tool map. One step is one model round-trip, including any tool calls in that response.</li><li><strong className="text-zinc-200">Stream and run tools.</strong> Text deltas and tool calls/results become typed events as they arrive. Tools enforce schemas, output caps, workspace boundaries, and read-before-write for existing files.</li><li><strong className="text-zinc-200">Record usage and check stop conditions.</strong> The assistant response joins the transcript. The loop stops if there were no tool calls, a budget was reached, the response hit its output limit, or cancellation occurred.</li><li><strong className="text-zinc-200">Continue with compacted context when needed.</strong> Older messages are summarized or truncated before the next step when the conversation itself gets large.</li><li><strong className="text-zinc-200">Persist.</strong> The transcript is appended to the session file and, when memory is on, the turn is extracted and the snapshot saved.</li></ol><Code language="text">{"prompt + prior messages + system + tools + memory index\n  → streamed model step\n  → text / tool calls / tool results\n  → append response and account usage\n  ├─ no tool calls or a stop condition → finish\n  └─ tools remain and budget allows → compact → next step"}</Code></DocSection>

    <DocSection id="budgets" title="Two different budgets"><p><code className="font-mono text-[11px] text-zinc-300">maxTokens</code> is a <em>spend</em> budget and accumulates across the whole run, so it stops a run that is over-consuming even when the context is small. It defaults to 400,000; set it to <code className="font-mono text-[11px] text-zinc-300">0</code> to disable the cap. The loop also defaults to 32 steps and 8,192 generated tokens per response.</p><p><code className="font-mono text-[11px] text-zinc-300">compactAtTokens</code> is a <em>context</em> budget, and the two are deliberately different. Because every step re-sends the whole transcript, cumulative usage roughly multiplies the real context size — triggering compaction off it compacted healthy runs and cost the agent its working memory mid-task. Compaction instead compares the size of the most recent request, taken from the provider&apos;s own reported input count, against the threshold. It runs only after a step that requested tools, and only when there is a middle section to summarize.</p><Note title="Compaction keeps tool pairs intact">The verbatim tail is extended backwards when necessary so a tool result is never separated from the tool call that produced it. An orphaned result makes the transcript unsendable and ends the run, so the tail boundary is aligned to whole tool rounds rather than a raw message count.</Note></DocSection>

    <DocSection id="steering" title="Steering a running turn"><p>A run is steerable from the host or the CLI. A message sent mid-run is appended to the transcript at the next step boundary — after the current step&apos;s tools settle, before the next model request — so it is never injected into a request that is already streaming.</p><Code language="ts">{"const run = runAgent(options);\n\nrun.steer(\"actually use TypeScript, not JavaScript\");\nrun.followUp(\"then update the changelog\");   // only if the run would otherwise finish\nrun.interrupt();                            // abort now\nrun.pending();                              // { steer: [], followUp: [] }\n"}</Code><p>Steers jump ahead of follow-ups, and each keeps its order. A steer <em>never</em> aborts the in-flight model call — <code className="font-mono text-[11px] text-zinc-300">interrupt()</code> is the separate action for that. Two details matter for reliability: a pending message prevents the run from ending (otherwise a message typed while the model was writing its final answer would be silently discarded), and a delivered message grants a fresh step window so <code className="font-mono text-[11px] text-zinc-300">maxSteps</code> cannot drop something a human deliberately sent.</p><p>Steers reach the model as ordinary <code className="font-mono text-[11px] text-zinc-300">user</code> messages, indistinguishable from any other turn. Nothing marks them.</p></DocSection>

    <DocSection id="cancellation" title="Stopping a turn that will not stop"><p>Tool execution receives the run&apos;s abort signal, so interrupting reaches a running command instead of merely looking like it did. A shell command that reads stdin gets EOF immediately rather than blocking until its timeout, and a timed-out command is killed as a process group so no grandchildren survive.</p><Code language="text">{"Ctrl-C   stop the running turn and say so\nCtrl-C   press again to exit the TUI\nCtrl-D   exit on an empty prompt"}</Code><Note title="Ctrl-C escalates">A single Ctrl-C would otherwise leave you trapped whenever a tool stopped responding, because the run could not exit while a turn was in flight. Forcing a kill skips terminal teardown and leaves the shell inside the alternate screen with raw mode still on, which is why NAH also restores mouse reporting, bracketed paste, the keyboard protocol and the cursor on SIGTERM, SIGHUP and uncaught errors.</Note></DocSection>

    <DocSection id="permissions" title="Tools and permissions"><p>The standard tools are <code>read</code>, <code>list</code>, <code>grep</code>, <code>glob</code>, <code>edit</code>, <code>write</code>, and <code>bash</code>. Read-only tools are never approval-gated. Edit, write, and bash pass through the configured policy; the SDK allows them if no callback is supplied.</p><p>In an interactive session NAH asks before mutations. Answer <code className="font-mono text-[11px] text-zinc-300">y</code> once, <code className="font-mono text-[11px] text-zinc-300">a</code> to allow that whole tool for the session, or <code className="font-mono text-[11px] text-zinc-300">A</code> for only that exact call. Scoping “always” to the exact command string meant a fresh prompt for every slightly different invocation, which read as the choice not being remembered.</p><p><code>readonly</code> denies mutations and <code>yolo</code> allows them. Print and JSON modes default to <code>yolo</code> because they cannot pause for a prompt, so pass <code>--permissions readonly</code> for a read-only one-shot run.</p><Link href="/docs/tools" className="text-violet-200 hover:text-white">Tool schemas, limits, and approval callbacks →</Link></DocSection>

    <DocSection id="result" title="Observe and use the result"><p><code className="font-mono text-[11px] text-zinc-300">runAgent</code> returns an async event stream and a result promise. The stream reports <code>run-start</code>, step boundaries, text deltas, tool activity, mid-turn user messages, compaction, and finish/error events. The result contains final text, stop reason, usage, transcript, step count and compaction count.</p><Code language="ts">{"const run = runAgent(options);\n\nfor await (const event of run.events) {\n  renderProgress(event);\n}\n\nconst result = await run.result;\nconsole.log(result.reason, result.steps, result.usage);"}</Code><p>The CLI adds session controls around a turn: continue or branch saved JSONL history, inspect usage and the task plan, view diffs, and undo supported workspace changes.</p><Link href="/docs/cli" className="text-violet-200 hover:text-white">CLI modes, sessions, and the TUI →</Link></DocSection>
  </DocsShell>;
}