import Link from "next/link";
import { Code, DocHeader, DocSection, DocsShell, Note } from "@/components/docs/DocsShell";

export default function AgentLoopPage() {
  return <DocsShell current="/docs/agent-loop"><DocHeader eyebrow="RUNTIME / AGENT LOOP" title="One visible step at a time." description="runAgent owns a small loop around AI SDK streaming. Each iteration makes one model round-trip, executes the requested tools, emits events, and then checks whether the run should continue." />
    <DocSection id="sequence" title="The run sequence"><p>Each step streams text and tool events as they arrive. The step ends after one model response and its tool executions. If the response contains tool calls, the runtime checks its budgets and either compacts the transcript or starts another step.</p><ol className="ml-5 list-decimal space-y-2"><li>The runtime appends the user prompt to any supplied prior messages.</li><li>It emits <code className="font-mono text-[11px] text-zinc-300">run-start</code> and starts a streamed model call.</li><li>Text deltas, tool calls, and tool results are emitted as typed events.</li><li>Usage is accumulated; the run stops on a final answer, step limit, token limit, abort, or error.</li><li>When enabled and over the compaction threshold, older transcript content is summarized or truncated before continuing.</li></ol><Code language="text">{"run-start\n  step-start → text-delta / tool-call / tool-result → step-finish\n  [optional compacted event]\n  ...\nfinish: completed | max-steps | max-tokens | aborted | error"}</Code></DocSection>
    <DocSection id="budgets" title="Budgets and defaults"><p>The loop defaults to a maximum of 32 steps and a cumulative token budget of 400,000. A step is one model round-trip plus its tool calls. Set <code className="font-mono text-[11px] text-zinc-300">maxTokens: 0</code> to disable the token cap. The compaction threshold defaults to 120,000 tokens and retains the most recent six messages by default.</p><p>Compaction defaults to <code className="font-mono text-[11px] text-zinc-300">model</code> when it runs. Use <code className="font-mono text-[11px] text-zinc-300">truncate</code> for lossy removal of older history or <code className="font-mono text-[11px] text-zinc-300">off</code> to disable compaction. Compaction is only considered when the run reaches its threshold and still has another step available.</p><Note title="What the cap means">Tool calls within the same streamed model response belong to one step. The step cap limits model round-trips; it is not a direct limit on the number of tool calls.</Note></DocSection>
    <DocSection id="result" title="Events and final result"><p><code className="font-mono text-[11px] text-zinc-300">runAgent</code> returns an async iterable of events and a result promise. The result includes final text, stop reason, usage, the final transcript, and compaction count. See the <Link href="/docs/events" className="text-violet-200 hover:text-white">streaming events guide</Link> for consuming the event union.</p><Code language="ts">{"const run = runAgent(options);\n\nfor await (const event of run.events) {\n  console.log(event.type, event);\n}\n\nconst result = await run.result;\nconsole.log(result.reason, result.usage);"}</Code></DocSection>
  </DocsShell>;
}
