import { Code, DocHeader, DocSection, DocsShell, Note } from "@/components/docs/DocsShell";

const tiers = [
  ["L0", "Registers", "Always injected. Active tensions, the proprioceptive self-model, and the active task trace."],
  ["L1", "Hot cache", "Pre-staged prompt context for the next turn, assembled while the previous reply streamed."],
  ["L2", "Warm store", "Indexed candidate memories offered to the arbiter for promotion, capped at 20 per turn."],
  ["L3", "Cold archive", "Historical memories that stay out of the prompt until something promotes them."],
];

const api = [
  ["getPromptContext(message?)", "Returns the memory block to prepend to the system prompt. Synchronous and under 1ms."],
  ["postTurnAsync({ userMessage, assistantResponse, detectedDomains? })", "Runs arbitration after the turn. Resolves once decisions and persistence are applied."],
  ["addMemory(item, targetTier = \"L2\")", "Adds or promotes a MemoryItem into a tier."],
  ["addTension(tension) / resolveTension(id, resolution)", "Registers or closes a contradiction pinned in L0."],
  ["recordDomainOutcome(domain, success, failurePattern?)", "Updates the moving-average reliability score for a domain."],
  ["getSnapshot() / loadSnapshot(snapshot)", "Serialize or restore the full L0–L3 state and stats."],
];

export default function MemoryPage() {
  return <DocsShell current="/docs/memory"><DocHeader eyebrow="MEMORY / COGNITIVE MEMORY" title="Memory that decides what matters." description="CognitiveMemory is an optional four-tier cache layer exported from the runtime. It keeps a small pinned core, pre-stages the next turn’s context, and does its expensive work after the reply has already streamed back." />
    <DocSection id="tiers" title="Four tiers, one prompt block"><div className="overflow-hidden rounded-xl border border-white/[0.08]"><div className="grid grid-cols-[36px_92px_1fr] border-b border-white/[0.07] bg-white/[0.025] px-4 py-2 font-mono text-[9px] uppercase tracking-widest text-zinc-600"><span>Tier</span><span>Name</span><span>Contents</span></div>{tiers.map(([tier, name, contents]) => <div key={tier} className="grid grid-cols-[36px_92px_1fr] border-b border-white/[0.06] px-4 py-3 last:border-0"><code className="font-mono text-[11px] text-violet-200">{tier}</code><span className="text-[11px] text-zinc-300">{name}</span><span className="text-xs leading-5 text-zinc-400">{contents}</span></div>)}</div><p>Only L0 and L1 reach the model. L2 and L3 are candidates, indexed and scanned but not injected. Nothing here is required for the agent loop to run — memory is an additive layer you construct yourself.</p></DocSection>
    <DocSection id="prompt-context" title="Pre-turn: build the prompt context"><p><code className="font-mono text-[11px] text-zinc-300">getPromptContext</code> synchronously concatenates the L0 core state and any pre-staged L1 items into a markdown block you prepend to the system prompt. It also runs the fast gate against the current user message and can prepend a premise-correction notice.</p><Code language="ts">{"import { CognitiveMemory } from \"@astracollab/not-another-harness\";\n\nconst memory = new CognitiveMemory({\n  maxL0Tokens: 2000,\n  maxL1Tokens: 8000,\n});\n\nconst system = [\n  basePrompt,\n  memory.getPromptContext(userMessage),\n].join(\"\\n\").trim();\n\nconst run = runAgent({ model, prompt: userMessage, system, tools });\nfor await (const event of run.events) { /* stream */ }\nawait run.result;\n\n// After the reply is done: arbitrate and pre-stage the next turn.\nawait memory.postTurnAsync({\n  userMessage,\n  assistantResponse: replyText,\n});"}</Code><Note title="Zero added time to first token">Prompt assembly is string concatenation, not a model call, so it adds no latency to the first streamed token. All arbitration happens after the turn completes.</Note></DocSection>
    <DocSection id="arbiter" title="Post-turn: the arbiter decides tiers"><p><code className="font-mono text-[11px] text-zinc-300">postTurnAsync</code> updates the active domains, sends up to twenty L2 candidates plus the current L1 summaries to the arbiter, then applies the returned promotions, demotions, pins, tensions, and self-model updates.</p><p>Without an arbiter, a built-in heuristic runs: candidates whose domains appear in the turn are promoted to L1, and L1 items whose domains have gone quiet are demoted once the hot cache exceeds five entries. Supply a fast model to make those calls smarter.</p><Code language="ts">{"import { createModelArbiter } from \"@astracollab/not-another-harness\";\n\nconst memory = new CognitiveMemory({\n  arbiter: createModelArbiter({ model: arbiterModel }),\n});"}</Code><p>An arbiter is just a function. It receives the turn text, the assistant reply, the L0 prompt, the L1 summaries, and the L2 candidates, and returns a structured <code className=\"font-mono text-[11px] text-zinc-300">ArbiterEvaluationResult</code>. A model-backed arbiter that throws returns an empty result instead of failing the turn, so memory stays stable.</p></DocSection>
    <DocSection id="fast-gate" title="The fast heuristic gate"><p>Before the model is called, a synchronous regex scanner checks the user message for explicit corrections (“actually, we switched to…”, “stop using…”, “disregard prior…”) and extracts domain keywords for auth, database, frontend, build, api, and git. A correction injects a short caution note into the memory block. It is heuristic, sub-5ms, and never calls a model.</p><Code language="ts">{"import { runFastGate, extractDomains } from \"@astracollab/not-another-harness\";\n\nconst gate = runFastGate(userMessage);\n// { action: \"proceed\" | \"inject_caution\", cautionNote?, detectedDomains? }\n\nawait memory.postTurnAsync({\n  userMessage,\n  assistantResponse: replyText,\n  detectedDomains: extractDomains(userMessage),\n});"}</Code></DocSection>
    <DocSection id="self-model" title="Self-model and knowledge tensions"><p>The self-model tracks per-domain reliability as a moving average over the last ten outcomes, plus known failure patterns and recommended strategies. Any active domain below 75% reliability is rendered into the L0 block as a proprioceptive guardrail, so weak areas get explicit attention instead of confident guesses.</p><Code language="ts">{"memory.recordDomainOutcome(\"css\", false, \"overwrites tokens without reading the theme file\");\n\nmemory.addTension({\n  id: \"tension-1\",\n  status: \"active\",\n  claimA: { source: \"user\", statement: \"We use Tailwind v3\", timestamp: Date.now() },\n  claimB: { source: \"package.json\", statement: \"tailwindcss: ^4.0.0\", timestamp: Date.now() },\n  impact: \"critical\",\n  taskRelevance: 1,\n  actionableQuestion: \"Which Tailwind version should the styles target?\",\n});\n\nmemory.resolveTension(\"tension-1\", { resolvedBy: \"user\", pattern: \"Tailwind v4 @theme syntax\" });"}</Code><p>Active tensions are pinned into every prompt block until they are resolved, each paired with an actionable question so the agent asks rather than guesses.</p></DocSection>
    <DocSection id="persistence" title="Persistence and snapshots"><p>Register <code className="font-mono text-[11px] text-zinc-300">onPersist</code> to receive a full state snapshot at the end of every turn, or take snapshots yourself to move memory between processes. Persistence failures are swallowed and never block a turn.</p><Code language="ts">{"const memory = new CognitiveMemory({\n  onPersist: async (state) => {\n    await writeFile(\".nah/memory.json\", JSON.stringify(state));\n  },\n});\n\nmemory.loadSnapshot(JSON.parse(await readFile(\".nah/memory.json\", \"utf8\")));"}</Code></DocSection>
    <DocSection id="api" title="API surface"><div className="space-y-2">{api.map(([name, desc]) => <div key={name} className="grid gap-1 rounded-lg border border-white/[0.06] bg-white/[0.02] px-3 py-2.5 sm:grid-cols-[220px_1fr] sm:gap-4"><code className="font-mono text-[10px] leading-5 text-violet-200">{name}</code><span className="text-xs leading-5 text-zinc-500">{desc}</span></div>)}</div><p>Types for every item above — <code className="font-mono text-[11px] text-zinc-300">MemoryItem</code>, <code className="font-mono text-[11px] text-zinc-300">MemoryTier</code>, <code className="font-mono text-[11px] text-zinc-300">KnowledgeTension</code>, <code className="font-mono text-[11px] text-zinc-300">ProprioceptiveSelfModel</code>, <code className="font-mono text-[11px] text-zinc-300">CognitiveMemoryOptions</code> — are exported from the package root alongside the class.</p></DocSection>
  </DocsShell>;
}