import { defineConfig } from "drizzle-kit"

/**
 * Drizzle Kit configuration.
 *
 * The schema is split across two files on purpose: `auth-schema.ts` is
 * generated by `pnpm auth:generate` and must never be hand-edited, while
 * `schema.ts` is the service's own tables. Both go into one migration folder so
 * the auth tables and the memory tables are created in the same transaction and
 * cannot drift apart.
 */
export default defineConfig({
  dialect: "sqlite",
  schema: ["./src/server/db/schema.ts", "./src/server/db/auth-schema.ts"],
  out: "./drizzle",
  dbCredentials: {
    url: process.env.COGNITIVE_MEMORY_DATABASE_PATH ?? ".cognitive-memory/CognitiveMemory.sqlite"
  },
  strict: true,
  verbose: true
})
