import { Code, DocHeader, DocSection, DocsShell, Note } from "@/components/docs/DocsShell";

export default function CliPage() {
  return <DocsShell current="/docs/cli"><DocHeader eyebrow="CLI / REFERENCE" title="A terminal interface to the same runtime." description="Use the interactive REPL for collaborative work, print mode for one-shot prompts, or JSON mode when another program needs the event stream." />
    <DocSection id="modes" title="Run modes"><Code>{"nah                              # interactive REPL\nnah \"fix the flaky test\"        # run prompt, then open REPL\nnah -p \"summarize this diff\"    # print answer and exit\nnah --mode json \"inspect auth\"  # JSONL events to stdout\ngit diff | nah -p \"review this\" # include stdin as prompt context"}</Code><p>Use <code className="font-mono text-[11px] text-zinc-300">@path</code> arguments to include file contents in the initial prompt, and <code className="font-mono text-[11px] text-zinc-300">--cwd</code> to select the workspace root.</p></DocSection>
    <DocSection id="options" title="Common options"><div className="space-y-2">{[["-m, --model", "provider:model-id, such as anthropic:claude-sonnet-4-5 or openai:gpt-4.1."], ["-c, --continue", "Continue the most recent session for this working directory."], ["--session <path>", "Load or continue a session at a specific path."], ["--no-session", "Keep the session in memory; do not persist it."], ["-y, --yolo", "Allow mutating tool calls without prompting."], ["--permissions", "Set ask, yolo, or readonly behavior."], ["--sandbox [name]", "Use a Blaxel sandbox; requires BL_API_KEY and BL_WORKSPACE."], ["-h, --help", "Print the full CLI help."]].map(([flag, desc]) => <div key={flag} className="grid gap-1 rounded-lg border border-white/[0.06] bg-white/[0.02] px-3 py-2.5 sm:grid-cols-[145px_1fr] sm:gap-4"><code className="font-mono text-[10px] text-violet-200">{flag}</code><span className="text-xs leading-5 text-zinc-500">{desc}</span></div>)}</div></DocSection>
    <DocSection id="permissions" title="Permission modes"><p>Interactive mode defaults to <code className="font-mono text-[11px] text-zinc-300">ask</code>. The first approval decision for a tool can be remembered for the session. Print and JSON modes default to <code className="font-mono text-[11px] text-zinc-300">yolo</code>, since the process cannot pause for an interactive prompt. Specify <code className="font-mono text-[11px] text-zinc-300">--permissions readonly</code> to make those modes read-only.</p><Code>{"nah --permissions readonly -p \"summarize src/auth\"\nnah --permissions ask --mode json \"inspect only\""}</Code></DocSection>
    <DocSection id="repl" title="REPL commands"><p>Within interactive mode, use these slash commands to manage the active session.</p><Code>{"/help                 Show commands\n/model <spec>         Switch model\n/permissions [mode]   Set ask, yolo, or readonly\n/stats                Show session token usage\n/compact              Compact the transcript using truncation\n/clear                Drop the current transcript\n/session new|off      Start a JSONL session file or stop persisting\n/quit                 Exit"}</Code><Note title="Session storage">The CLI persists conversations as JSONL by default. Use <code>--no-session</code> to opt out for a run; the REPL also provides session controls.</Note></DocSection>
  </DocsShell>;
}
