import {
  account,
  invitation,
  member,
  organization,
  session,
  user,
  verification
} from "./auth-schema"

/**
 * The Better Auth tables as one object, keyed the way `drizzle({ schema })` and
 * `drizzleAdapter` look them up.
 *
 * Kept out of `auth-schema.ts` on purpose: that file is regenerated by
 * `pnpm auth:generate` and anything hand-written there would be overwritten.
 */
export const authTables = {
  user,
  session,
  account,
  verification,
  organization,
  member,
  invitation
} as const

export { account, invitation, member, organization, session, user, verification }
