import { relations } from "drizzle-orm"
import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core"

import { authTables, organization } from "./auth-tables"

/**
 * Storage for the memory service.
 *
 * Tenants are Better Auth `organization` rows: identity, sessions, invitations
 * and roles live in `./auth-schema` (generated by `pnpm auth:generate`), and
 * everything here hangs off `organizationId`. That is what makes "this key can
 * only reach its own memory" a join rather than a convention.
 *
 * Timestamps are ISO-8601 text. SQLite has no date type, and ISO text sorts
 * lexicographically in chronological order, which is exactly what the `ORDER BY`
 * clauses below rely on. Better Auth's own tables use integer epoch ms; the two
 * conventions are kept apart deliberately rather than converted on every read.
 */

export const apiKeys = sqliteTable(
  "api_keys",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id")
      .notNull()
      .references(() => organization.id, { onDelete: "cascade" }),
    /** Human label, e.g. "cli laptop". */
    name: text("name").notNull(),
    /**
     * Public, non-secret half: `cmi_<env>_<id>`. Indexed so a presented key is
     * one lookup rather than a scan, and shown in the UI so a key can be
     * identified without being disclosed.
     */
    prefix: text("prefix").notNull(),
    /** sha256 of the secret half. The secret itself is never stored. */
    secretHash: text("secret_hash").notNull(),
    /** JSON array of scope strings. */
    scopes: text("scopes", { mode: "json" }).$type<Array<string>>().notNull().default([]),
    lastUsedAt: text("last_used_at"),
    revokedAt: text("revoked_at"),
    expiresAt: text("expires_at"),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull()
  },
  (table) => [
    uniqueIndex("api_keys_prefix_idx").on(table.prefix),
    index("api_keys_organization_idx").on(table.organizationId)
  ]
)

export const memories = sqliteTable(
  "memories",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull(),
    content: text("content").notNull(),
    /** Dense one-liner used to pre-stage and to show in the index. */
    bookmark: text("bookmark").notNull(),
    /** Short label for the always-present index; falls back to a truncation. */
    gist: text("gist"),
    /** L0 | L1 | L2 | L3 — see the tier docs in the README. */
    tier: text("tier").notNull(),
    domains: text("domains", { mode: "json" }).$type<Array<string>>().notNull().default([]),
    accessCount: integer("access_count").notNull().default(0),
    lastAccessedAt: text("last_accessed_at").notNull(),
    /** Set when the memory was learned from a specific conversation. */
    sourceSessionId: text("source_session_id"),
    /** "rules" | "model" | "api" — where the statement came from. */
    source: text("source").notNull().default("api"),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull()
  },
  (table) => [
    index("memories_organization_tier_idx").on(table.organizationId, table.tier),
    index("memories_organization_recent_idx").on(table.organizationId, table.lastAccessedAt),
    index("memories_session_idx").on(table.organizationId, table.sourceSessionId)
  ]
)

export const tensions = sqliteTable(
  "tensions",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull(),
    /** active | latent | resolved */
    status: text("status").notNull().default("active"),
    claimA: text("claim_a", { mode: "json" }).$type<Claim>().notNull(),
    claimB: text("claim_b", { mode: "json" }).$type<Claim>().notNull(),
    /** low | medium | critical */
    impact: text("impact").notNull().default("low"),
    taskRelevance: real("task_relevance").notNull().default(1),
    actionableQuestion: text("actionable_question").notNull(),
    resolution: text("resolution", { mode: "json" }).$type<Resolution | null>(),
    createdAt: text("created_at").notNull(),
    updatedAt: text("updated_at").notNull()
  },
  (table) => [index("tensions_organization_status_idx").on(table.organizationId, table.status)]
)

/**
 * Per-organisation overrides of the injection budgets.
 *
 * Nullable on purpose: a null column means "inherit the deployment default", so
 * turning a setting back on is a matter of clearing one field rather than
 * remembering what the deployment default was at the time. The dashboard shows
 * both the override and the effective value, because a budget that silently
 * reverted to a deployment default is the kind of thing that shows up as "the
 * prompt got smaller and nobody changed anything".
 */
export const organizationSettings = sqliteTable("organization_settings", {
  organizationId: text("organization_id").primaryKey(),
  maxTotalTokens: integer("max_total_tokens"),
  maxIndexItems: integer("max_index_items"),
  defaultRecallLimit: integer("default_recall_limit"),
  /** How long injections, usage and outcomes are kept. 0 keeps them forever. */
  retentionDays: integer("retention_days").notNull().default(90),
  /** "auto" uses the model when one is configured; "rules" never does. */
  extraction: text("extraction").notNull().default("auto")
})

/**
 * What the service actually put in a prompt, and why.
 *
 * `usage_events` answers "how many tokens", which is a cost question. This
 * answers "was it the right memory", which is the only question that tells you
 * whether to raise the budget or fix the store — a build that spent its whole
 * budget on index lines is not fixed by a bigger ceiling.
 *
 * The rendered block is stored rather than reconstructed. Re-running the planner
 * against today's memory would show what the agent *would* get now, which is a
 * different and more flattering answer than the one that was actually sent.
 */
export const injectionLogs = sqliteTable(
  "injection_logs",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull(),
    apiKeyId: text("api_key_id"),
    tokens: integer("tokens").notNull().default(0),
    truncated: integer("truncated", { mode: "boolean" }).notNull().default(false),
    /** Lines included at index cost, i.e. gist only. */
    indexLines: integer("index_lines").notNull().default(0),
    /** Lines that were promoted to a full body by a deterministic signal. */
    bodies: integer("bodies").notNull().default(0),
    /** Identifiers the triggering message named. Why the triggers fired. */
    identifiers: text("identifiers", { mode: "json" }).$type<Array<string>>().notNull().default([]),
    /** reason -> count, so the mix survives without walking the entries. */
    reasons: text("reasons", { mode: "json" }).$type<Record<string, number>>().notNull().default({}),
    entries: text("entries", { mode: "json" }).$type<Array<InjectionLogEntry>>().notNull().default([]),
    /** The exact block that was handed to the caller. */
    text: text("text").notNull().default(""),
    createdAt: text("created_at").notNull()
  },
  (table) => [index("injection_logs_organization_idx").on(table.organizationId, table.createdAt)]
)

/**
 * One recorded task outcome, so reliability has a history behind it.
 *
 * `self_models` keeps the current score per domain, which is enough to render a
 * guardrail but not enough to answer "is this getting better or did one bad
 * afternoon cause it". The score is a weighted moving average; the only way to
 * see the individual samples is to have kept them.
 */
export const domainOutcomes = sqliteTable(
  "domain_outcomes",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull(),
    domain: text("domain").notNull(),
    success: integer("success", { mode: "boolean" }).notNull(),
    failurePattern: text("failure_pattern"),
    strategy: text("strategy"),
    createdAt: text("created_at").notNull()
  },
  (table) => [
    index("domain_outcomes_organization_idx").on(table.organizationId, table.createdAt),
    index("domain_outcomes_domain_idx").on(table.organizationId, table.domain)
  ]
)

export const selfModels = sqliteTable("self_models", {
  organizationId: text("organization_id").primaryKey(),
  /** JSON map of domain -> capability record. */
  domains: text("domains", { mode: "json" })
    .$type<Record<string, DomainCapability>>()
    .notNull()
    .default({}),
  calibrationFactor: real("calibration_factor").notNull().default(1),
  activeDomains: text("active_domains", { mode: "json" }).$type<Array<string>>().notNull().default([]),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull()
})

/** Per-request accounting, so a dashboard can show what memory is costing. */
export const usageEvents = sqliteTable(
  "usage_events",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull(),
    apiKeyId: text("api_key_id"),
    /** Which endpoint was called. */
    route: text("route").notNull(),
    /** Tokens memory put into the prompt, when the call was a context build. */
    injectedTokens: integer("injected_tokens"),
    createdAt: text("created_at").notNull()
  },
  (table) => [index("usage_events_organization_idx").on(table.organizationId, table.createdAt)]
)

export type Claim = {
  readonly source: string
  readonly statement: string
  readonly timestamp: number
}

export type Resolution = {
  readonly resolvedAt: number
  readonly resolvedBy: string
  readonly pattern: string
}

export type DomainCapability = {
  readonly reliabilityScore: number
  readonly sampleCount: number
  readonly knownFailurePatterns: Array<string>
  readonly recommendedStrategies: Array<string>
}

/** One line of a stored injection, as it was billed. */
export type InjectionLogEntry = {
  readonly id: string
  readonly tier: string
  readonly reason: string
  readonly gist: string
  readonly tokens: number
}

export * from "./auth-schema"

export const apiKeysRelations = relations(apiKeys, ({ one }) => ({
  organization: one(organization, {
    fields: [apiKeys.organizationId],
    references: [organization.id]
  })
}))

export const memoriesRelations = relations(memories, ({ one }) => ({
  organization: one(organization, {
    fields: [memories.organizationId],
    references: [organization.id]
  })
}))

/**
 * Everything in one object, which is what `drizzle({ schema })` expects for
 * relational queries. The generated auth tables are spread in so they resolve by
 * name alongside ours.
 */
export const schema = {
  ...authTables,
  apiKeys,
  memories,
  tensions,
  selfModels,
  usageEvents,
  organizationSettings,
  injectionLogs,
  domainOutcomes
}
