import { Code, DocHeader, DocSection, DocsShell, Note } from "@/components/docs/DocsShell";

export default function EventsPage() {
  return <DocsShell current="/docs/events"><DocHeader eyebrow="RUNTIME / STREAMING EVENTS" title="Observe the run as it happens." description="Each run exposes a typed async event stream alongside a promise for the final result. Build a terminal renderer, UI, audit log, or JSONL output around the same events." />
    <DocSection id="consume" title="Consume events"><p>Start the run, consume its event stream, then await the result. Event consumption is optional, but it is the way to observe progress while the model and tools run.</p><Code language="ts">{"const run = runAgent({ model, prompt, system, tools });\n\nfor await (const event of run.events) {\n  switch (event.type) {\n    case \"text-delta\":\n      process.stdout.write(event.text);\n      break;\n    case \"tool-call\":\n      console.log(\"tool\", event.toolName, event.input);\n      break;\n    case \"tool-result\":\n      console.log(\"result\", event.output, event.isError);\n      break;\n  }\n}\n\nconst result = await run.result;"}</Code><Note title="Stream and result are separate">The event stream reports incremental activity. The result promise resolves with the completed transcript, stop reason, usage totals, and compaction count.</Note></DocSection>
    <DocSection id="event-types" title="Event types"><div className="space-y-2">{[["run-start", "Step and token budgets for the run."], ["step-start", "The next model round-trip is starting."], ["text-delta", "A streamed text fragment."], ["tool-call", "Tool name, input, call ID, and step."], ["tool-result", "Capped textual output and error flag."], ["step-finish", "Cumulative usage at the end of a step."], ["compacted", "Transcript counts and summary size after compaction."], ["finish", "Final stop reason, assistant text, and usage."], ["error", "An error emitted before the run rejects."]].map(([name, desc]) => <div key={name} className="grid gap-1 rounded-lg border border-white/[0.06] bg-white/[0.02] px-3 py-2.5 sm:grid-cols-[125px_1fr] sm:gap-4"><code className="font-mono text-[10px] text-violet-200">{name}</code><span className="text-xs leading-5 text-zinc-500">{desc}</span></div>)}</div><p>The <code className="font-mono text-[11px] text-zinc-300">finish.reason</code> is one of <code className="font-mono text-[11px] text-zinc-300">completed</code>, <code className="font-mono text-[11px] text-zinc-300">max-steps</code>, <code className="font-mono text-[11px] text-zinc-300">max-tokens</code>, <code className="font-mono text-[11px] text-zinc-300">aborted</code>, or <code className="font-mono text-[11px] text-zinc-300">error</code>.</p></DocSection>
    <DocSection id="abort" title="Cancellation and errors"><p>Pass an <code className="font-mono text-[11px] text-zinc-300">AbortSignal</code> through <code className="font-mono text-[11px] text-zinc-300">abortSignal</code> to request cancellation. An aborted run emits a finish event with reason <code className="font-mono text-[11px] text-zinc-300">aborted</code>. Other failures emit an error event and reject the result promise, so handle that promise with your normal error handling.</p><Code language="ts">{"const controller = new AbortController();\nconst run = runAgent({ ...options, abortSignal: controller.signal });\n\nsetTimeout(() => controller.abort(), 30_000);\ntry {\n  const result = await run.result;\n} catch (error) {\n  console.error(\"Agent run failed\", error);\n}"}</Code></DocSection>
  </DocsShell>;
}
