import { Code, DocHeader, DocSection, DocsShell, Note } from "@/components/docs/DocsShell";

export default function ToolsPage() {
  return <DocsShell current="/docs/tools"><DocHeader eyebrow="RUNTIME / BUILT-IN TOOLS" title="Small tools with hard edges." description="The default coding tools expose common repository operations directly. Their schemas and outputs are bounded so the model can work in smaller, inspectable steps." />
    <DocSection id="catalog" title="The built-in set"><div className="overflow-hidden rounded-xl border border-white/[0.08]"><div className="grid grid-cols-[100px_1fr] border-b border-white/[0.07] bg-white/[0.025] px-4 py-2 font-mono text-[9px] uppercase tracking-widest text-zinc-600"><span>Tool</span><span>Purpose</span></div>{[["read", "Read a text file with 1-based line numbers and paging."], ["list", "List a directory tree with depth and output limits."], ["grep", "Search file contents and return capped path:line matches."], ["edit", "Apply an exact replacement to a file."], ["write", "Create or replace a text file."], ["bash", "Run a shell command with a timeout; included by default."]].map(([name, summary]) => <div key={name} className="grid grid-cols-[100px_1fr] border-b border-white/[0.06] px-4 py-3 last:border-0"><code className="font-mono text-[11px] text-violet-200">{name}</code><span className="text-xs leading-5 text-zinc-400">{summary}</span></div>)}</div><p>The default filesystem environment roots paths to the selected workspace and rejects paths that escape it. The grep implementation walks the workspace in-process; it does not require ripgrep.</p></DocSection>
    <DocSection id="permissions" title="Approval gates"><p>By default, read, list, and grep are not approval-gated. Mutating tools—edit, write, and bash—can be wrapped with an approval callback. If no callback is provided to the SDK, those calls are allowed.</p><Code language="ts">{"const tools = createCodingTools(environment, {\n  withBash: false,\n  requireReadBeforeWrite: true,\n  approveToolCall: async (toolName, input) => {\n    return await askUserToApprove(toolName, input);\n  },\n});"}</Code><Note title="Read before write">The default is to require a file to be read before the edit or overwrite tools change it. Set <code>requireReadBeforeWrite: false</code> only if your workflow intentionally removes that safeguard.</Note></DocSection>
    <DocSection id="caps" title="Output caps and boundaries"><p>Tool outputs are capped by the package defaults to keep large files and broad searches from overwhelming the conversation. File reads can be paged with offsets and limits. Directory listing and grep also return bounded results. Check <code className="font-mono text-[11px] text-zinc-300">DEFAULT_CAPS</code> in the package if your integration needs to understand those limits.</p><p>The Node environment confines file operations to the configured root. Bash commands execute with that root as their working directory and a timeout; shell behavior is still shell behavior, so use approval gates appropriate to your environment.</p></DocSection>
    <DocSection id="custom" title="Bring your own tools"><p><code className="font-mono text-[11px] text-zinc-300">runAgent</code> accepts a tool map compatible with the AI SDK tool set. Use the built-in tools as a starting point, or provide your own tools to limit capabilities or connect another execution backend.</p></DocSection>
  </DocsShell>;
}
