import { Code, DocHeader, DocSection, DocsShell, Note } from "@/components/docs/DocsShell";

const catalog = [
  ["read", "Read a text file with 1-based line numbers and paging."],
  ["list", "List a directory tree with depth and output limits."],
  ["glob", "Find files by name or path pattern: *, **, ?, {a,b}."],
  ["grep", "Search file contents and return capped path:line matches."],
  ["edit", "Apply an exact replacement to a file."],
  ["write", "Create or replace a text file."],
  ["bash", "Run a shell command with a timeout; included by default."],
  ["recall", "Search this project's memory. Read-only, and CLI-registered."],
];

export default function ToolsPage() {
  return <DocsShell current="/docs/tools"><DocHeader eyebrow="RUNTIME / BUILT-IN TOOLS" title="Small tools with hard edges." description="The default coding tools expose common repository operations directly. Their schemas and outputs are bounded so the model can work in smaller, inspectable steps." />
    <DocSection id="catalog" title="The built-in set"><div className="overflow-hidden rounded-xl border border-white/[0.08]"><div className="grid grid-cols-[100px_1fr] border-b border-white/[0.07] bg-white/[0.025] px-4 py-2 font-mono text-[9px] uppercase tracking-widest text-zinc-600"><span>Tool</span><span>Purpose</span></div>{catalog.map(([name, summary]) => <div key={name} className="grid grid-cols-[100px_1fr] border-b border-white/[0.06] px-4 py-3 last:border-0"><code className="font-mono text-[11px] text-violet-200">{name}</code><span className="text-xs leading-5 text-zinc-400">{summary}</span></div>)}</div><p>The filesystem environment roots paths to the selected workspace and rejects paths that escape it. Grep and glob walk the workspace in-process and do not require ripgrep.</p></DocSection>

    <DocSection id="glob" title="Why glob exists"><p>Discovery by name pattern is the primitive that keeps an agent from guessing paths or walking a tree level by level. It skips straight to the pattern&apos;s literal prefix, so a rooted pattern never traverses the rest of the repository.</p><Code language="ts">{"glob { pattern: \"**/page.tsx\" }\nglob { pattern: \"apps/*/src/**/*.tsx\" }\nglob { pattern: \"**/*.{test,spec}.ts\" }\ngrep { pattern: \"DocsShell\", path: \"apps/nah/**/*.tsx\" }"}</Code><p><code>grep</code> accepts a glob in <code>path</code> too, which is usually the fastest way to find the code that references something. Both skip <code>node_modules</code>, <code>.git</code> and build output; pass <code>includeHidden</code> to opt back into dotfiles.</p><p><code>glob</code> is registered automatically when the environment implements it, and can be turned off with <code>withGlob: false</code>.</p></DocSection>

    <DocSection id="permissions" title="Approval gates"><p>Read-only tools — read, list, grep, glob — are never gated. Mutating tools (edit, write, bash) can be wrapped with an approval callback. If no callback is provided to the SDK, those calls are allowed.</p><Code language="ts">{"const tools = createCodingTools(environment, {\n  withBash: false,\n  requireReadBeforeWrite: true,\n  approveToolCall: async (toolName, input) => {\n    return await askUserToApprove(toolName, input);\n  },\n});"}</Code><Note title="Read before write">The default is to require a file to be read before the edit or overwrite tools change it. Path spellings are normalised first, so <code>./a.ts</code> and <code>a.ts</code> are treated as the same file — otherwise a valid edit gets rejected over spelling rather than substance. Set <code>requireReadBeforeWrite: false</code> only if your workflow intentionally removes that safeguard.</Note><p>“Always allow” is scoped to the tool for the session. Scoping it to the exact command string meant the agent asked again for every slightly different invocation, which read as the choice not being remembered at all.</p></DocSection>

    <DocSection id="bash" title="Shell behaviour"><p>Commands run with the workspace root as their working directory and a timeout, and the whole process group is killed on timeout so no backgrounded child survives.</p><Code language="text">{"stdin is closed for the command, never an open pipe"}</Code><Note title="Commands that read stdin used to hang">An inherited, never-written stdin pipe meant any command reading stdin — `sed` with no file, `cat`, `grep` with no arguments — blocked until the timeout, two minutes at the default. That reads as a stuck agent. Those commands now get EOF immediately.</Note></DocSection>

    <DocSection id="caps" title="Output caps and boundaries"><p>Tool outputs are capped by the package defaults so large files and broad searches cannot overwhelm the conversation. Reads page with offsets and limits; listing, grep and glob are bounded too. Check <code className="font-mono text-[11px] text-zinc-300">DEFAULT_CAPS</code> if your integration needs those limits.</p><p>Repeated identical tool calls collapse in the transcript to a single line with a tally, and successful read-only results are not echoed — the call itself already says what happened.</p></DocSection>

    <DocSection id="custom" title="Bring your own tools"><p><code className="font-mono text-[11px] text-zinc-300">runAgent</code> accepts any AI SDK v5 tool map. Use the built-ins as a starting point, or supply your own to limit capabilities or connect another execution backend.</p></DocSection>
  </DocsShell>;
}